image: gitpod/workspace-full:2023-01-16-03-31-28
tasks:
  - name: Set up shell aliases 
    init: |
      mkdir -p /workspace/.persist
      cp .bash_aliases $HOME/.bash_aliases  # make it available in current session
      cp .bash_aliases /workspace/.persist  # so we can restore it if workspace times out
  - name: install staticcheck
    init: go install honnef.co/go/tools/cmd/staticcheck@latest  # fix for 'Analysis Tools Missing' warning in status bar
  - name: Go Get Fetcher # https://www.gitpod.io/docs/languages/go/#start-up-tasks
    init: go get -v -t -d ./...
  - name: Restore shell aliases
    before: |
	  # Runs when workspace is resumed after idle timeout
      cp /workspace/.persist/.bash_alias $HOME;
      exit;
  - name: Install tctl # for backwards compatibility 
    command: |
      mkdir -p tctl_temp
      pushd tctl_temp
      curl -sL -O https://github.com/temporalio/tctl/releases/download/v1.18.0/tctl_1.18.0_linux_amd64.tar.gz
      tar zxvf tctl_1.18*
      mv tctl /workspace/bin/tctl
      chmod +x /workspace/bin/tctl
      popd
      rm -rf tctl_temp
  - name: Temporal Local Development Server
    init: |
      # install the Temporal CLI (overriding the default installation directory)
      curl -sSf https://temporal.download/cli.sh | sh -s - --dir /workspace
    command: |
      source /workspace/edu-101-go-code/.bash_aliases
      export TEMPORAL_NOTIFY_ON_NEW_VERSION=false
      export TEMPORAL_CORS_ORIGINS=http://localhost:3000
      /workspace/bin/temporal server start-dev --ui-port 8080 --db-filename $HOME/.cluster-persistence.db
  - name: Worker
    command: |
      echo "waiting for server...."
      gp ports await 7233 && gp ports await 8080 && sleep 25 && gp preview $(gp url 8080)
      clear
      echo "Use this terminal to start your worker."
      source /workspace/edu-101-go-code/.bash_aliases
    openMode: tab-after
  - name: Terminal
    command: |
      gp open README.md
      clear
      echo "Use this terminal to run commands.."
      source /workspace/edu-101-go-code/.bash_aliases
    openMode: split-right

ports:
  - name: Temporal server's Frontend service
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # custom port, as per --ui-port option above
    description: Temporal Web UI
    onOpen: ignore
    visibility: private
  - name: Greeting Service
    description: Local microservice used in exercises
    port: 9999
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
