image: temporalio/gitpod-edu:1.1
tasks:
    # task adds the shell config file to a persistent directory
  - name: Shell configuration
    init: |
      mv .bash.cfg /workspace
      gp sync-done shell-config
      exit;
    # task fixes the 'Analysis Tools Missing' warning in status bar
  - name: install staticcheck
    init: go install honnef.co/go/tools/cmd/staticcheck@latest  
    # task retrieves the project dependencies
  - name: Go Get Fetcher 
    init: go get -v -t -d ./...
    # task starts the Temporal Service via the CLI
  - name: Temporal Local Development Server
    command: |
      export TEMPORAL_NOTIFY_ON_NEW_VERSION=false
      export TEMPORAL_CORS_ORIGINS=http://localhost:3000
      temporal server start-dev \
        --ui-port 8080 \
        --db-filename /workspace/.cluster-persistence.db
    openMode: tab-after
  - name: Worker
    command: |
      gp sync-await shell-config
      source /workspace/.bash.cfg
      echo "Waiting for server...."
      gp ports await 7233 && gp ports await 8080 && gp preview $(gp url 8080)
      clear
      echo "Use this terminal to start your Worker."
  - name: Terminal
    command: |
      gp sync-await shell-config
      source /workspace/.bash.cfg
      gp open README.md
      clear
      echo "Use this terminal to run commands.."
    openMode: split-right

ports:
  - name: Temporal server's Frontend service
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # custom port, as per --ui-port option above
    description: Temporal Web UI
    onOpen: ignore
    visibility: private
  - name: Greeting Service
    description: Local microservice used in exercises
    port: 9999
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - ms-python.debugpy
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
