image: temporalio/gitpod-edu:1.0
tasks:
  - name: Set up shell aliases 
    init: |
      # Copy Temporal-specific executables to a directory that is in the $PATH
	  mkdir -p "$HOME/.local/bin"
	  cp -R /home/linuxbrew/.linuxbrew/bin/* "$HOME/.local/bin"
      mkdir -p /workspace/.persist
      cp .bash_aliases $HOME/               # make it available in current session
      cp .bash_aliases /workspace/.persist  # so we can restore it if workspace times out
  - name: install staticcheck
    init: go install honnef.co/go/tools/cmd/staticcheck@latest  # fix for 'Analysis Tools Missing' warning in status bar
  - name: Go Get Fetcher # https://www.gitpod.io/docs/languages/go/#start-up-tasks
    init: go get -v -t -d ./...
  - name: Restore shell aliases
    before: |
      # Runs when workspace is resumed after idle timeout
      cp /workspace/.persist/.bash_aliases $HOME/;
      source /workspace/edu-101-go-code/.bash_aliases
      export TEMPORAL_NOTIFY_ON_NEW_VERSION=false
      export TEMPORAL_CORS_ORIGINS=http://localhost:3000
      exit;
  - name: Temporal Local Development Server
    command: |
      source /workspace/edu-101-go-code/.bash_aliases
      export TEMPORAL_NOTIFY_ON_NEW_VERSION=false
      export TEMPORAL_CORS_ORIGINS=http://localhost:3000
      /workspace/bin/temporal server start-dev --ui-port 8080 --db-filename $workspace/.cluster-persistence.db
    openMode: tab-after
  - name: Worker
    command: |
      echo "waiting for server...."
      gp ports await 7233 && gp ports await 8080 && sleep 25 && gp preview $(gp url 8080)
      clear
      echo "Use this terminal to start your Worker."
      source /workspace/edu-101-go-code/.bash_aliases
  - name: Terminal
    command: |
      gp open README.md
      clear
      echo "Use this terminal to run commands.."
      source /workspace/edu-101-go-code/.bash_aliases
    openMode: split-right

ports:
  - name: Temporal server's Frontend service
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # custom port, as per --ui-port option above
    description: Temporal Web UI
    onOpen: ignore
    visibility: private
  - name: Greeting Service
    description: Local microservice used in exercises
    port: 9999
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - ms-python.debugpy
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
